### PR TITLE
Pyinstall should obey the -i flag

### PR DESCRIPTION
**Pull request by Wilfred**
The user should be able to override the PyPI instance used with the -i flag. Our tests also use this ability. Currently, the configuration always wins.

### CODE REVIEW

**Comment by Wilfred** [comment]
Hold up, I've not fixed it yet! :)

**Comment by eeaston** [comment]
Hmm, it came up as a merge request though?

**Comment by Wilfred** [comment]
Yep. I had two commits, one adding a failing unit test, and a separate to fix it. I wanted to open the pull request with just the failing test to see Travis show the test fail. I would then push my second commit to see Travis show the test pass.

If I just push them together, Travis only runs the tests on the last commit, so I haven't verified that the test fails when it should.

**Comment by Wilfred** [comment]
After chatting to someone more familiar with Travis, I'm told I don't need to create a pull request to have Travis test my branches. Handy! I'll make sure my pull requests are only code that's ready to merge in future.

**Pull request merged**
